#!/usr/bin/env python3
"""Validate ESAF controls and generate deterministic catalog views."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import yaml
from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[1]
CONTROLS = ROOT / "controls"
SCHEMA_PATH = CONTROLS / "schema" / "control.schema.json"
CATALOG_JSON = CONTROLS / "catalog.json"
CATALOG_MD = CONTROLS / "CATALOG.md"
CONTROL_ID = re.compile(r"^[A-Z]{3}-[1-9][0-9]{2}$")
OBJECTIVE_ID = re.compile(r"\*\*([A-Z]{3}-[0-9]{2})\s")
RELATED_ID = re.compile(r"`([A-Z]{3}-[1-9][0-9]{2})(?:\([1-9][0-9]*\))?`")
ASSESSMENT = re.compile(r"^- \*\*([A-Z]{3}-[1-9][0-9]{2})-A[1-9][0-9]* - (Examine|Interview|Test|Observe):\*\*", re.MULTILINE)
EXTERNAL_MAPPING_HEADING = re.compile(r"^## External mappings$", re.MULTILINE)
REQUIRED_SECTIONS = (
    "Requirement",
    "Intent",
    "Applicability",
    "Implementation guidance",
    "Expected evidence",
    "Assessment procedures",
    "Metrics",
    "Enhancements",
    "Related controls",
    "External mappings",
    "Change history",
)
EXPECTED_EXTERNAL_MAPPING = (
    "Authoritative external mappings are maintained in the "
    "[ESAF-1600 generated catalog](../../crosswalks/CATALOG.md)."
)


def parse_control(path: Path) -> tuple[dict, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("missing YAML front matter")
    try:
        _, front_matter, body = text.split("---", 2)
    except ValueError as exc:
        raise ValueError("malformed YAML front matter") from exc
    metadata = yaml.safe_load(front_matter)
    if not isinstance(metadata, dict):
        raise ValueError("front matter must be a mapping")
    return metadata, body.strip() + "\n"


def section(body: str, heading: str) -> str:
    match = re.search(
        rf"^## {re.escape(heading)}\s*$\n(.*?)(?=^## |\Z)",
        body,
        flags=re.MULTILINE | re.DOTALL,
    )
    return match.group(1).strip() if match else ""


def load_objectives() -> dict[str, str]:
    text = (CONTROLS / "OBJECTIVES.md").read_text(encoding="utf-8")
    objectives: dict[str, str] = {}
    for line in text.splitlines():
        match = OBJECTIVE_ID.search(line)
        if match:
            objective_id = match.group(1)
            objectives[objective_id] = line.split("**", 2)[-1].strip()
    return objectives


def render_json(records: list[dict], objectives: dict[str, str], families: list[str]) -> str:
    family_counts = Counter(record["family"] for record in records)
    baseline_counts = Counter(value for record in records for value in record["baselines"])
    pillar_counts = Counter(value for record in records for value in record["pillars"])
    lifecycle_counts = Counter(value for record in records for value in record["lifecycle_stages"])
    document = {
        "schema_version": "1.0.0",
        "generated_from": "controls/<family>/<control-id>.md",
        "control_count": len(records),
        "objective_count": len(objectives),
        "families": {family: family_counts[family] for family in families},
        "baseline_coverage": dict(sorted(baseline_counts.items())),
        "pillar_coverage": dict(sorted(pillar_counts.items())),
        "lifecycle_coverage": dict(sorted(lifecycle_counts.items())),
        "controls": records,
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def render_markdown(records: list[dict], objectives: dict[str, str], families: list[str]) -> str:
    family_records = defaultdict(list)
    for record in records:
        family_records[record["family"]].append(record)
    baseline_counts = Counter(value for record in records for value in record["baselines"])
    pillar_counts = Counter(value for record in records for value in record["pillars"])
    lifecycle_counts = Counter(value for record in records for value in record["lifecycle_stages"])
    lines = [
        "# ESAF Control Catalog",
        "",
        "> Generated by `tools/validate_controls.py`. Do not edit directly.",
        "",
        f"The catalog contains **{len(records)} base controls** implementing **{len(objectives)} objectives** across **{len(families)} families**.",
        "",
        "## Family coverage",
        "",
        "| Family | Controls | Objectives |",
        "|---|---:|---:|",
    ]
    for family in families:
        objective_count = sum(1 for objective in objectives if objective.startswith(f"{family}-"))
        lines.append(f"| [{family}]({family}/README.md) | {len(family_records[family])} | {objective_count} |")
    lines.extend(["", "## Baseline coverage", "", "| Baseline | Controls |", "|---|---:|"])
    for name in ("E0", "E1", "E2", "E3", "E4"):
        lines.append(f"| {name} | {baseline_counts[name]} |")
    lines.extend(["", "## Pillar coverage", "", "| Pillar | Controls |", "|---|---:|"])
    for name in ("protect", "utilize", "govern"):
        lines.append(f"| {name.title()} | {pillar_counts[name]} |")
    lines.extend(["", "## Lifecycle coverage", "", "| Lifecycle stage | Controls |", "|---|---:|"])
    for name, count in sorted(lifecycle_counts.items()):
        lines.append(f"| {name.replace('_', ' ').title()} | {count} |")
    lines.extend(["", "## Control index", ""])
    for family in families:
        lines.extend([f"### {family}", "", "| Control | Objective | Title | Status | Baselines |", "|---|---|---|---|---|"])
        for record in family_records[family]:
            lines.append(
                f"| [{record['id']}]({record['path']}) | {record['objective']} | {record['title']} | "
                f"{record['status'].title()} | {', '.join(record['baselines']) or 'None'} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def validate() -> tuple[list[str], list[dict], dict[str, str], list[str]]:
    errors: list[str] = []
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    validator = Draft202012Validator(schema)
    families = list(schema["properties"]["family"]["enum"])
    objectives = load_objectives()
    records: list[dict] = []
    seen_ids: set[str] = set()
    covered_objectives: Counter = Counter()
    pending_related: list[tuple[str, str]] = []

    paths = sorted(
        (path for family in families for path in (CONTROLS / family).glob("*.md") if CONTROL_ID.match(path.stem)),
        key=lambda path: (families.index(path.parent.name), path.name),
    )
    for path in paths:
        relative = path.relative_to(ROOT).as_posix()
        try:
            metadata, body = parse_control(path)
        except (OSError, ValueError, yaml.YAMLError) as exc:
            errors.append(f"{relative}: {exc}")
            continue
        for validation_error in sorted(validator.iter_errors(metadata), key=lambda item: list(item.path)):
            location = ".".join(str(part) for part in validation_error.path) or "metadata"
            errors.append(f"{relative}: {location}: {validation_error.message}")
        control_id = metadata.get("id", "")
        if path.stem != control_id:
            errors.append(f"{relative}: filename does not match id {control_id!r}")
        if path.parent.name != metadata.get("family"):
            errors.append(f"{relative}: directory does not match family {metadata.get('family')!r}")
        if control_id in seen_ids:
            errors.append(f"{relative}: duplicate control id {control_id}")
        seen_ids.add(control_id)
        objective = metadata.get("objective", "")
        if objective not in objectives:
            errors.append(f"{relative}: unknown objective {objective!r}")
        covered_objectives[objective] += 1
        expected_heading = f"# {control_id} {metadata.get('title', '')}"
        if not body.startswith(expected_heading + "\n"):
            errors.append(f"{relative}: expected heading {expected_heading!r}")
        for heading in REQUIRED_SECTIONS:
            if not section(body, heading):
                errors.append(f"{relative}: missing or empty section '## {heading}'")
        external_heading_count = len(EXTERNAL_MAPPING_HEADING.findall(body))
        if external_heading_count != 1:
            errors.append(
                f"{relative}: expected exactly one '## External mappings' heading; "
                f"found {external_heading_count}"
            )
        elif section(body, "External mappings") != EXPECTED_EXTERNAL_MAPPING:
            errors.append(f"{relative}: External mappings must delegate to ESAF-1600")
        requirement = section(body, "Requirement")
        if len(re.findall(r"\bshall\b", requirement, flags=re.IGNORECASE)) != 1:
            errors.append(f"{relative}: Requirement must contain exactly one 'shall'")
        procedures = ASSESSMENT.findall(section(body, "Assessment procedures"))
        if not procedures:
            errors.append(f"{relative}: no valid assessment procedure found")
        for procedure_id, _method in procedures:
            if procedure_id != control_id:
                errors.append(f"{relative}: assessment id {procedure_id} does not match {control_id}")
        for related in RELATED_ID.findall(section(body, "Related controls")):
            pending_related.append((relative, related))
        record = dict(metadata)
        record["path"] = relative.removeprefix("controls/")
        records.append(record)

    all_ids = {record.get("id") for record in records}
    for relative, related in pending_related:
        if related not in all_ids:
            errors.append(f"{relative}: unresolved related control {related}")
    for objective in objectives:
        count = covered_objectives[objective]
        if count != 1:
            errors.append(f"controls/OBJECTIVES.md: objective {objective} is implemented by {count} controls; expected 1")
    for family in families:
        numbers = [int(record["id"].split("-")[1]) for record in records if record.get("family") == family]
        expected = list(range(100, 100 + 10 * len(numbers), 10))
        if numbers != expected:
            errors.append(f"controls/{family}: control numbering {numbers} does not match {expected}")
        index = (CONTROLS / family / "README.md").read_text(encoding="utf-8")
        for record in (item for item in records if item.get("family") == family):
            if f"[{record['id']}]({record['id']}.md)" not in index:
                errors.append(f"controls/{family}/README.md: missing index link for {record['id']}")
    for path in ROOT.rglob("*.md"):
        if ".git" not in path.parts:
            text = path.read_text(encoding="utf-8")
            if "�" in text or "â€" in text or "â†" in text:
                errors.append(f"{path.relative_to(ROOT).as_posix()}: possible text-encoding corruption")
    return errors, records, objectives, families


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="validate sources and confirm generated files are current")
    mode.add_argument("--write", action="store_true", help="validate sources and update generated catalog files")
    args = parser.parse_args()
    errors, records, objectives, families = validate()
    json_output = render_json(records, objectives, families)
    markdown_output = render_markdown(records, objectives, families)
    if args.write and not errors:
        CATALOG_JSON.write_text(json_output, encoding="utf-8", newline="\n")
        CATALOG_MD.write_text(markdown_output, encoding="utf-8", newline="\n")
    if args.check:
        for path, expected in ((CATALOG_JSON, json_output), (CATALOG_MD, markdown_output)):
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                errors.append(f"{path.relative_to(ROOT).as_posix()}: generated output is missing or stale; run with --write")
    if errors:
        print(f"Control catalog validation failed with {len(errors)} error(s):", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    action = "updated" if args.write else "validated"
    print(f"Successfully {action} {len(records)} controls, {len(objectives)} objectives, and {len(families)} families.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
